#!/usr/bin/env bash

set -euo pipefail
shopt -s globstar nullglob

LABEL=${CHECK_RUN_REPORTER_LABEL:-$GITHUB_ACTION}
ROOT=${CHECK_RUN_REPORTER_ROOT:-$(pwd)}
SHA=$GITHUB_SHA
TOKEN=$CHECK_RUN_REPORTER_TOKEN
URL=${CHECK_RUN_REPORTER_URL:-https://api.check-run-reporter.com/api/v1/submissions}
REPORT_DIR=$CHECK_RUN_REPORTER_REPORT

log 'Running check-run-reporter/action with the following parameters'
log "LABEL=$LABEL"
log "ROOT=$ROOT"
log "SHA=$SHA"

CMD="curl -v $URL"
CMD="$CMD --user token:'$TOKEN'"
CMD="$CMD -F label'=$LABEL'"
CMD="$CMD -F root='$ROOT'"
CMD="$CMD -F sha='$SHA'"

for FILE in $REPORT_DIR; do
  echo "Preparing to upload '$FILE' to Check Run Reporter"
  CMD="$CMD -F 'report=@$(pwd)/$FILE'"
done

echo "Uploading reports to Check Run Reporter"
OUT=$(eval "$CMD")

if [[ $OUT =~ code ]]; then
  echo 'Failed to upload to Check Run Reporter'
  echo "$OUT"
  exit 1
fi

echo "Uploaded reports to Check Run Reporter"
